something = input('Write something: ')
print('Primitive type of this value is', type(something))
print('Is numeric?', something.isnumeric())
print('Is alphabets?', something.isalpha())
print('Is alphanumeric?', something.isalnum())
print('Is lowercase?', something.islower())
print('Is uppercase?', something.isupper())
print('Is capitalize?', something.istitle())
print('Is printable?', something.isprintable())
print('Is only space?', something.isspace())
