print('Please, choose your numbers')
firstNumber = input('First number: ')
secondNumber = input('Second number: ')
sum = int(firstNumber) + int(secondNumber)
print('Sum of {} and {} is {}'.format(firstNumber, secondNumber, sum))
